### ISSUE TITLE
_load_user_token     base_path = self._get_base_path(self._user.path) AttributeError: 'str' object has no attribute 'path'

### ISSUE THREAD

**Issue by max-allan-surevine** [kubernetes-client/python-base#182]
```
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from kubernetes import config
>>> config.load_kube_config('/tmp/kubeconfig')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kubernetes/config/kube_config.py", line 649, in load_kube_config
    loader.load_and_set(config)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kubernetes/config/kube_config.py", line 461, in load_and_set
    self._load_authentication()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kubernetes/config/kube_config.py", line 205, in _load_authentication
    if self._load_user_token():
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kubernetes/config/kube_config.py", line 395, in _load_user_token
    base_path = self._get_base_path(self._user.path)
AttributeError: 'str' object has no attribute 'path'
```

Kubeconfig : 
```
Kind: config
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0...Qo=
    server: https://0...C.sk1.eu-west-2.eks.amazonaws.com
  name: k8s
contexts:
- context:
    cluster: k8s
    user: aws
  name: aws
current-context: aws
users:
- name: aws
  user: lambda
```

This _used_ to work with previous versions.
Other people have the same issue, "resolved" by pinning to version 9 of kubernetes.
https://github.com/aws-samples/amazon-k8s-node-drainer/issues/14

**Comment by roycaihw** [comment]
This is a regression introduced in https://github.com/kubernetes-client/python-base/pull/94. 

Technically a user with a string value (`user: lambda`) doesn't provide any auth info, and when we `_load_authentication` it should be a noop. [_get_base_path](https://github.com/kubernetes-client/python-base/blob/d30f1e6fd4e2725aae04fa2f4982a4cfec7c682b/config/kube_config.py#L484) expects `path` from `_user` because in most cases [_user would be a dict or list](https://github.com/kubernetes-client/python-base/blob/d30f1e6fd4e2725aae04fa2f4982a4cfec7c682b/config/kube_config.py#L256), which gets converted to a [ConfigNode](https://github.com/kubernetes-client/python-base/blob/d30f1e6fd4e2725aae04fa2f4982a4cfec7c682b/config/kube_config.py#L589-L590).

A workaround is to change your kubeconfig to make `user` a dict or a list, instead of a string. E.g.
```
users:
- name: aws
  user:
    name: lambda
```

We should fix the behavior in this client and add a test. I can think of either constructing a ConfigNode around the string value, or skipping [_load_user_token](https://github.com/kubernetes-client/python-base/blob/d30f1e6fd4e2725aae04fa2f4982a4cfec7c682b/config/kube_config.py#L483-L491) when `_user` doesn't have those token keys. I need to think which way makes more sense.
